/** Common */
export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const HANDLE_RADIO_CHANGE = 'HANDLE_RADIO_CHANGE';
export const HANDLE_SWITCH_CHANGE = 'HANDLE_SWITCH_CHANGE';
export const HANDLE_CHECKBOX_CHANGE = 'HANDLE_CHECKBOX_CHANGE';
export const HANDLE_IMAGE_FILE_CHANGE = 'HANDLE_IMAGE_FILE_CHANGE';
export const HANDLE_SELECT_CHANGE = 'HANDLE_SELECT_CHANGE';
export const HANDLE_STEP_CHANGE = 'HANDLE_STEP_CHANGE';
export const HANDLE_TAB_CHANGE = 'HANDLE_TAB_CHANGE';
export const HANDLE_LOADING_REQUEST = 'HANDLE_LOADING_REQUEST';
export const HANDLE_ERROR_REQUEST = 'HANDLE_ERROR_REQUEST';
export const HANDLE_ERROR_WITH_MESSAGE_REQUEST = 'HANDLE_ERROR_WITH_MESSAGE_REQUEST';
export const HANDLE_SUCCESS_REQUEST = 'HANDLE_SUCCESS_REQUEST';
export const HANDLE_SET_ADRESS_VIA_CEP = 'HANDLE_SET_ADRESS_VIA_CEP';
export const HANDLE_RESET_ADRESS_VIA_CEP = 'HANDLE_RESET_ADRESS_VIA_CEP';